/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardRoadmapsRouteImport } from './routes/dashboard.roadmaps'
import { Route as DashboardResumeRouteImport } from './routes/dashboard.resume'
import { Route as DashboardResourcesRouteImport } from './routes/dashboard.resources'
import { Route as DashboardQuizRouteImport } from './routes/dashboard.quiz'
import { Route as DashboardMentorRouteImport } from './routes/dashboard.mentor'
import { Route as DashboardJobsRouteImport } from './routes/dashboard.jobs'
import { Route as DashboardCareersRouteImport } from './routes/dashboard.careers'
import { Route as DashboardRoadmapKeyRouteImport } from './routes/dashboard.roadmap.$key'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoadmapsRoute = DashboardRoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumeRoute = DashboardResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResourcesRoute = DashboardResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuizRoute = DashboardQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMentorRoute = DashboardMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCareersRoute = DashboardCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoadmapKeyRoute = DashboardRoadmapKeyRouteImport.update({
  id: '/roadmap/$key',
  path: '/roadmap/$key',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/careers': typeof DashboardCareersRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/quiz': typeof DashboardQuizRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/roadmaps': typeof DashboardRoadmapsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/roadmap/$key': typeof DashboardRoadmapKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/careers': typeof DashboardCareersRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/quiz': typeof DashboardQuizRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/roadmaps': typeof DashboardRoadmapsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/roadmap/$key': typeof DashboardRoadmapKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/careers': typeof DashboardCareersRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/mentor': typeof DashboardMentorRoute
  '/dashboard/quiz': typeof DashboardQuizRoute
  '/dashboard/resources': typeof DashboardResourcesRoute
  '/dashboard/resume': typeof DashboardResumeRoute
  '/dashboard/roadmaps': typeof DashboardRoadmapsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/roadmap/$key': typeof DashboardRoadmapKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/careers'
    | '/dashboard/jobs'
    | '/dashboard/mentor'
    | '/dashboard/quiz'
    | '/dashboard/resources'
    | '/dashboard/resume'
    | '/dashboard/roadmaps'
    | '/dashboard/'
    | '/dashboard/roadmap/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/careers'
    | '/dashboard/jobs'
    | '/dashboard/mentor'
    | '/dashboard/quiz'
    | '/dashboard/resources'
    | '/dashboard/resume'
    | '/dashboard/roadmaps'
    | '/dashboard'
    | '/dashboard/roadmap/$key'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/careers'
    | '/dashboard/jobs'
    | '/dashboard/mentor'
    | '/dashboard/quiz'
    | '/dashboard/resources'
    | '/dashboard/resume'
    | '/dashboard/roadmaps'
    | '/dashboard/'
    | '/dashboard/roadmap/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roadmaps': {
      id: '/dashboard/roadmaps'
      path: '/roadmaps'
      fullPath: '/dashboard/roadmaps'
      preLoaderRoute: typeof DashboardRoadmapsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resume': {
      id: '/dashboard/resume'
      path: '/resume'
      fullPath: '/dashboard/resume'
      preLoaderRoute: typeof DashboardResumeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resources': {
      id: '/dashboard/resources'
      path: '/resources'
      fullPath: '/dashboard/resources'
      preLoaderRoute: typeof DashboardResourcesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quiz': {
      id: '/dashboard/quiz'
      path: '/quiz'
      fullPath: '/dashboard/quiz'
      preLoaderRoute: typeof DashboardQuizRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mentor': {
      id: '/dashboard/mentor'
      path: '/mentor'
      fullPath: '/dashboard/mentor'
      preLoaderRoute: typeof DashboardMentorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/careers': {
      id: '/dashboard/careers'
      path: '/careers'
      fullPath: '/dashboard/careers'
      preLoaderRoute: typeof DashboardCareersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roadmap/$key': {
      id: '/dashboard/roadmap/$key'
      path: '/roadmap/$key'
      fullPath: '/dashboard/roadmap/$key'
      preLoaderRoute: typeof DashboardRoadmapKeyRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCareersRoute: typeof DashboardCareersRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardMentorRoute: typeof DashboardMentorRoute
  DashboardQuizRoute: typeof DashboardQuizRoute
  DashboardResourcesRoute: typeof DashboardResourcesRoute
  DashboardResumeRoute: typeof DashboardResumeRoute
  DashboardRoadmapsRoute: typeof DashboardRoadmapsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardRoadmapKeyRoute: typeof DashboardRoadmapKeyRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCareersRoute: DashboardCareersRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardMentorRoute: DashboardMentorRoute,
  DashboardQuizRoute: DashboardQuizRoute,
  DashboardResourcesRoute: DashboardResourcesRoute,
  DashboardResumeRoute: DashboardResumeRoute,
  DashboardRoadmapsRoute: DashboardRoadmapsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardRoadmapKeyRoute: DashboardRoadmapKeyRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
